# Base Configuration for Velora HFT Platform
# This file contains default settings shared across all environments

# ============================================================================
# LOGGING CONFIGURATION
# ============================================================================
[logging]
level = "info"
# file = "logs/velora.log"  # Uncomment to enable file logging

# ============================================================================
# DATABASE CONFIGURATION
# ============================================================================
[database]
backend = "questdb"  # Options: "inmemory", "questdb", "timescaledb"

[database.questdb]
host = "localhost"
pg_port = 8812
http_port = 9000
ilp_port = 9009
database = "qdb"
username = "admin"
password = "quest"
pool_size = 10

[database.timescaledb]
host = "localhost"
port = 5432
database = "hft"
username = "admin"
password = "admin123"
pool_size = 10
ssl = false

# ============================================================================
# ENGINE CONFIGURATION
# ============================================================================
[engine.backtest]
initial_capital = 10000.0
commission_rate = 0.001  # 0.1%
slippage_rate = 0.0001   # 0.01%

[engine.live]
dry_run = true
order_timeout_seconds = 30
position_check_interval_ms = 1000

# ============================================================================
# RISK MANAGEMENT CONFIGURATION
# ============================================================================
[risk]
max_position_size = 1000.0
max_total_exposure = 10000.0
max_drawdown_percent = 20.0
max_daily_loss = 500.0

# Per-symbol position limits (optional)
[risk.position_limits]
# "BTC/USD" = 5000.0
# "ETH/USD" = 10000.0

# ============================================================================
# EXCHANGE CONFIGURATIONS
# ============================================================================
# Exchanges are defined per environment since they require different credentials
# See environment-specific configs (testing.toml, paper-trading.toml, etc.)
